<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Libraries */

$this->title = $model->No_;
$this->params['breadcrumbs'][] = ['label' => 'Libraries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="libraries-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->No_], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->No_], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'timestamp',
            'No_',
            'Description',
            'Search Description',
            'Description 2',
            'FA Class Code',
            'FA Subclass Code',
            'Global Dimension 1 Code',
            'Global Dimension 2 Code',
            'Location Code',
            'FA Location Code',
            'Vendor No_',
            'Main Asset_Component',
            'Component of Main Asset',
            'Budgeted Asset',
            'Warranty Date',
            'Responsible Employee',
            'Serial No_',
            'Last Date Modified',
            'Blocked',
            'Picture',
            'Maintenance Vendor No_',
            'Under Maintenance',
            'Next Service Date',
            'Inactive',
            'No_ Series',
            'FA Posting Group',
            'Acq_ date',
            'Supplier',
            'Invoice no_',
            'Cost',
            'Depr_ Rate',
            'Acc Depreciation',
            'Fixed Asset Type',
            'Max_ Carrying Capacity',
            'Registration No',
            'Parastatl Reg_ No',
            'Make',
            'YOM',
            'C_C',
            'Duty',
            'Rating',
            'Body',
            'Model',
            'Car Rating',
            'Language Code (Default)',
            'Attachement',
            'Disposed',
            'Tracking Date',
            'Tracking Renewal date',
            'Car Tracking Company',
            'Fuel Consumption Km_Ltr',
            'Maturity Period',
            'No_ Of Interest Periods',
            'Status',
            'Investment Type Name',
            'No_Of Units',
            'Asset Type',
            'Interest Rate Type',
            'Acquisition Cost',
            'Rate _',
            'Issue Date',
            'Term (Days)',
            'Purchase Type',
            'Disposal Value',
            'Revaluations',
            'Interest Received',
            'Dividend Received',
            'Balance',
            'Investment Type',
            'Interest Frequency Period',
            'Maturity Date',
            'Investment Date',
            'Investment Posting Group',
            'Maturity Period Days',
            'Accrued Interest',
            'Interest at purchase',
            'Valuation Method',
            'RBA Class',
            'Purchase Link',
            'Sale Link',
            'Interest Link',
            'Disposal Status',
            'Method of Disposal',
            'Valuation Amount',
            'Reserve Price',
            'Disposal Committee Meeting',
            'Log Book No_',
            'Policy No',
            'Last Valued Date',
            'Valuer',
            'Premium Amount',
            'Valuation Firm',
            'Date of Commencement',
            'Expiry Date',
            'Insurer',
            'Date of Purchase',
            'Amount of Purchase',
            'Insurance Company',
            'Service Provider',
            'Service Provider Name',
            'Service Intervals',
            'Date Last Serviced',
            'Next Service',
            'Amount',
            'Service_Repair Description',
            'Manufacturer',
            'Asset Bar Code',
            'Lease Term',
            'Lease Start Date',
            'Lease End Date',
            'On Lease',
            'Author',
            'ISBN',
            'Category',
            'Category Name',
            'Availability',
            'approved',
            'Donations Reference No',
            'donation?',
            'requested?',
            'Date donated_Bought',
            'Lost?',
            'Classification No',
            'Publisher',
            'Date_Year of Publication',
            'Pagination',
            'Copies Available',
            'Accession number',
            'Purchased Date',
            'Subject',
            'Place of Publication',
        ],
    ]) ?>

</div>
